//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Console.StudentWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetStudent_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/GetStudent")]
    public partial class GetStudent : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExportStudentsToCSVOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallGetStudentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetStudent() {
            this.Url = global::Console.Properties.Settings.Default.Console_StudentWS_GetStudent;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExportStudentsToCSVCompletedEventHandler ExportStudentsToCSVCompleted;
        
        /// <remarks/>
        public event CallGetStudentCompletedEventHandler CallGetStudentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/GetStudent:ExportStudentsToCSV", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/GetStudent", ResponseElementName="ExportStudentsToCSV_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/GetStudent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportStudentsToCSV() {
            this.Invoke("ExportStudentsToCSV", new object[0]);
        }
        
        /// <remarks/>
        public void ExportStudentsToCSVAsync() {
            this.ExportStudentsToCSVAsync(null);
        }
        
        /// <remarks/>
        public void ExportStudentsToCSVAsync(object userState) {
            if ((this.ExportStudentsToCSVOperationCompleted == null)) {
                this.ExportStudentsToCSVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportStudentsToCSVOperationCompleted);
            }
            this.InvokeAsync("ExportStudentsToCSV", new object[0], this.ExportStudentsToCSVOperationCompleted, userState);
        }
        
        private void OnExportStudentsToCSVOperationCompleted(object arg) {
            if ((this.ExportStudentsToCSVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportStudentsToCSVCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/GetStudent:GetStudent", RequestElementName="GetStudent", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/GetStudent", ResponseElementName="GetStudent_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/GetStudent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CallGetStudent(ref string num) {
            object[] results = this.Invoke("CallGetStudent", new object[] {
                        num});
            num = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallGetStudentAsync(string num) {
            this.CallGetStudentAsync(num, null);
        }
        
        /// <remarks/>
        public void CallGetStudentAsync(string num, object userState) {
            if ((this.CallGetStudentOperationCompleted == null)) {
                this.CallGetStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetStudentOperationCompleted);
            }
            this.InvokeAsync("CallGetStudent", new object[] {
                        num}, this.CallGetStudentOperationCompleted, userState);
        }
        
        private void OnCallGetStudentOperationCompleted(object arg) {
            if ((this.CallGetStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGetStudentCompleted(this, new CallGetStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ExportStudentsToCSVCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CallGetStudentCompletedEventHandler(object sender, CallGetStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGetStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGetStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string num {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591